site_name: Classroom Dark Mode
site_url: https://classroomdarkmode.ryanluu.dev
site_author: Ryan Luu
site_description: Dark mode extension for Google Classroom based on Material 2 guidelines.

repo_name: RyanLua/ClassroomDarkMode
repo_url: https://github.com/RyanLua/ClassroomDarkMode

copyright: Copyright &copy; Ryan Luu

theme:
  name: material

  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: light blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: light blue
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

  features:
    - content.tooltips
    - navigation.instant
    - navigation.instant.progress
    - navigation.tracking
    - navigation.top
    - navigation.footer

extra_css:
  - stylesheets/extra.css
